### ISSUE TITLE
Cuda error: no kernel image is available for execution on the device #31285

### ISSUE THREAD

**Issue by CiaraG98** [huggingface/transfer-learning-conv-ai#101]
I get this error when trying to fine-tune the model with train.py with my own dataset. Using cuda 11.2 and pytorch 1.7.1+cu110. 
When running with CPU the training seems to make my laptop restart with some error, so I am trying to run with GPU instead. 

Is there something I am missing that is making this not work?

**Comment by CiaraG98** [comment]
Resolved this by installing **conda install pytorch==1.2.0 torchvision==0.4.0 cudatoolkit=10.0 -c pytorch
 pip install install torch==1.3.0 pytorch-ignite transformers==2.5.1 tensorboardX==1.8 tensorflow spacy**
